// Generated by generate-apple-everest-stage25kj-decals.py from exact public inputs.
using System;
using System.Collections.Generic;
namespace Celeste.Mod;
internal static class AppleEverestSelectedDecalRegistry
{
    internal static readonly HashSet<string> IgnoredNames = new(StringComparer.Ordinal);
    internal static void Apply(Decal decal)
    {
        string name = decal.Name.ToLower();
        if (name.StartsWith("decals/", StringComparison.Ordinal)) name = name.Substring(7);
        switch (name)
        {
            case "junglehelper/jungle0-general/plantgrass":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(4f, 4f, 1, 0.05f, false, 1f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "junglehelper/jungle0-general/plantgrassshort":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(2f, 2f, 1, 0.05f, false, 1f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "junglehelper/jungle0-general/plantfiddlegrass":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(3f, 2.5f, 1, 0.05f, false, 0f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "junglehelper/jungle3-ruins/vinechang":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(2f, 3f, 1, 0.05f, true, 0f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "junglehelper/jungle3-ruins/vinechangb":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(2f, 3f, 1, 0.05f, true, 0f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "junglehelper/jungle3-ruins/vinechangc":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(2f, 3f, 1, 0.05f, true, 0f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/jizo_game_a":
            case "sj2021/beginnerlobby/jizo_game_b":
            case "sj2021/beginnerlobby/jizo_game_c":
            case "sj2021/beginnerlobby/jizo_hat":
            case "sj2021/beginnerlobby/jizo_large":
            case "sj2021/beginnerlobby/jizo_larger":
            case "sj2021/beginnerlobby/jizo_largest_clothed":
            case "sj2021/beginnerlobby/jizo_largest_snake":
            case "sj2021/beginnerlobby/jizo_largest_watcher":
            case "sj2021/beginnerlobby/jizo_medium":
            case "sj2021/beginnerlobby/jizo_small":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(0, 0, 16, 32);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/ivy/rimhoriza":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -900101;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/ivy/dimdiagb":
            case "sj2021/mosscairn/fg/ivy/dimhoriza":
            case "sj2021/mosscairn/fg/ivy/dimhorizb":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -900004;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/bg_jizo_medium":
            case "sj2021/beginnerlobby/bg_jizo_small":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(0, 0, 16, 32);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/ivy/leafab":
            case "sj2021/mosscairn/fg/ivy/leafac":
            case "sj2021/mosscairn/fg/ivy/leafad":
            case "sj2021/mosscairn/fg/ivy/leafae":
            case "sj2021/mosscairn/fg/ivy/leafaf":
            case "sj2021/mosscairn/fg/ivy/leafbb":
            case "sj2021/mosscairn/fg/ivy/leafbc":
            case "sj2021/mosscairn/fg/ivy/leafbd":
            case "sj2021/mosscairn/fg/ivy/leafbe":
            case "sj2021/mosscairn/fg/ivy/leafbf":
            case "sj2021/mosscairn/fg/ivy/leafbigadim":
            case "sj2021/mosscairn/fg/ivy/leafca":
            case "sj2021/mosscairn/fg/ivy/leafcd":
            case "sj2021/mosscairn/fg/ivy/leafcf":
            case "sj2021/mosscairn/fg/ivy/leafdd":
            case "sj2021/mosscairn/fg/ivy/leafde":
            case "sj2021/mosscairn/fg/ivy/leafdf":
            case "sj2021/mosscairn/fg/ivy/leafstema":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -900008;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/ivy/lightdiaga":
            case "sj2021/mosscairn/fg/ivy/lightdiagb":
            case "sj2021/mosscairn/fg/ivy/lightverta":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -900006;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/cave/coral/coral_":
            case "sj2021/beginnerlobby/cave/coral/coral_b":
            case "sj2021/beginnerlobby/cave/coral/coral_c":
            case "sj2021/beginnerlobby/cave/coral/coral_d":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(32, 48, "2-7", "0", "1", "8-12");
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/bamboo/depth_bamboo_top_b":
                decal.AppleEverestBeginRegistry();
                decal.Depth = 15000;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/tileblend/bg/beginner_lobby_cave_bg":
            case "sj2021/beginnerlobby/tileblend/bg/beginner_lobby_cave_bg_a":
            case "sj2021/beginnerlobby/tileblend/bg/bgbrickruined_a":
            case "sj2021/beginnerlobby/tileblend/bg/quinnigan":
                decal.AppleEverestBeginRegistry();
                decal.Depth = 10010;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/cave/stalagtite_a":
            case "sj2021/beginnerlobby/cave/stalagtite_b":
            case "sj2021/beginnerlobby/cave/stalagtite_c":
            case "sj2021/beginnerlobby/cave/stalagtite_d":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-24, -16, 48, 32);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/hangplanta":
            case "sj2021/beginnerlobby/waterfall/hangplantb":
            case "sj2021/beginnerlobby/waterfall/hangplantc":
            case "sj2021/beginnerlobby/waterfall/hangplantd":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(1f, 1f, 1, 1f, true, 0f, false);
                decal.AppleEverestStaticMover(-8, -10, 16, 2);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterrocka":
            case "sj2021/beginnerlobby/waterfall/waterrockaalt":
            case "sj2021/beginnerlobby/waterfall/waterrockb":
            case "sj2021/beginnerlobby/waterfall/waterrockbalt":
            case "sj2021/beginnerlobby/waterfall/waterrockc":
            case "sj2021/beginnerlobby/waterfall/waterrockcalt":
            case "sj2021/beginnerlobby/waterfall/waterrockd":
            case "sj2021/beginnerlobby/waterfall/waterrockdalt":
            case "sj2021/beginnerlobby/waterfall/waterrocke":
            case "sj2021/beginnerlobby/waterfall/waterrockealt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(0, 0, 32, 32);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/watergrassa":
            case "sj2021/beginnerlobby/waterfall/watergrassb":
            case "sj2021/beginnerlobby/waterfall/watergrassc":
            case "sj2021/beginnerlobby/waterfall/watergrassd":
            case "sj2021/beginnerlobby/waterfall/watergrasse":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(1f, 1f, 1, 1f, false, 0f, false);
                decal.AppleEverestStaticMover(-8, 8, 16, 2);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterflowera":
            case "sj2021/beginnerlobby/waterfall/waterflowerb":
            case "sj2021/beginnerlobby/waterfall/waterflowerc":
            case "sj2021/beginnerlobby/waterfall/waterflowerd":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(0, 0, 16, 16);
                decal.AppleEverestBloom(0f, 0f, 0.5f, 10f);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waves/wavea":
                decal.AppleEverestBeginRegistry();
                decal.Depth = 10001;
                decal.AppleEverestRandomizeFrame();
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/pinwheel":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 10f;
                decal.AppleEverestRandomizeFrame();
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/small_pinwheel":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 12f;
                decal.AppleEverestRandomizeFrame();
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/roofcenter":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestSolid(-12, -4, 24, 6, 14);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/g_roofcenter":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestSolid(-12, -4, 24, 6, 14);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/prologue/carved-edge-left":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestSolid(-8, -8, 8, 13, 5);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/prologue/carved-edge-right":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestSolid(-4, -8, 8, 13, 5);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbricka":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickaalt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickb":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickbalt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickc":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickcalt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickd":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickdalt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbricke":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/waterbrickealt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 8, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/weirdmossa":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 16);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/weirdmossd":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 16);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/weirdmosse":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 16);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/weirdmossb":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/beginnerlobby/waterfall/weirdmossc":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestStaticMover(-8, -8, 16, 8);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/circumplex/floor soap a/floor soap a ":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 5f;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/circumplex/floor soap b/floor soap b ":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 5f;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/circumplex/soap bubbles a/soap bubbles a ":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 5f;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/circumplex/soap bubbles c/soap bubbles c ":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 5f;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/circumplex/soap bubbles e/soap bubbles e ":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 5f;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/hanky/flower_a_alt":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestLight(0f, -5f, "FFFFFF", 0.75f, 16, 5);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/snolls/animals/runaway/rabbit":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(35, 320, "0*9,10*2,0*19,6,7,8,9,0*18,6,8,9,0*2", "21", "0", "11,12,13,14,15,16,17,18,19,20");
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/snolls/animals/hover/bug/fly/a/fly":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(0, 48, "0,2,3,2,0,2,0,1", "0", "0", "0");
                decal.AppleEverestFloaty();
                decal.AppleEverestSetParallax(0.02f);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/snolls/animals/hover/bug/fly/e/fly":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(0, 48, "1,2,0,3,0,2,0,2,3,0", "0", "0", "0");
                decal.AnimationSpeed = 11f;
                decal.AppleEverestSetParallax(0.008f);
                decal.AppleEverestFloaty();
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/snolls/animals/misc/spider/b/hanging_spider_a":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(108, 250, "20", "57", "57-34,31,28,25-21,20*3", "20*4,21,24,27,30,33,36,39,42,45,48,51-56");
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/snolls/animals/hover/bug/bee/c/bee":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestScared(16, 24, "0,1,2,0,2,0,1,2,0,2,1", "0,2", "1", "1");
                decal.AppleEverestSetParallax(0.05f);
                decal.AppleEverestFloaty();
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/scenes/curtain_side_a":
                decal.AppleEverestBeginRegistry();
                decal.AppleEverestBanner(2f, 2f, 2, 0.05f, true, 0f, false);
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/wooddropshadowa":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -10010;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/wooddropshadowb":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -10010;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/mosscairn/fg/wooddropshadowwide":
                decal.AppleEverestBeginRegistry();
                decal.Depth = -10010;
                decal.AppleEverestEndRegistry();
                break;
            case "sj2021/quinnigan/tile_roses/top_a":
                decal.AppleEverestBeginRegistry();
                decal.AnimationSpeed = 6f;
                decal.AppleEverestEndRegistry();
                break;
        }
    }
}
