<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AppleEverestBuilder.Tests</AssemblyName>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AppleEverestBuilder.csproj" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <Compile Remove="HookSemantics/**/*.cs" />
  </ItemGroup>
</Project>
