#!/usr/bin/env python3
"""Emit typed, fail-closed authored-profile guards from the exact SJ metadata."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def cs(value):
    if isinstance(value, str): return json.dumps(value, ensure_ascii=True)
    if isinstance(value, bool): return str(value).lower()
    if isinstance(value, int): return str(value)
    return repr(value) + 'f'

def generate(doc):
    profiles = {}
    for row in doc['occurrences']:
        key = row['kind'] + ':' + row['customId']
        profiles.setdefault(key, {})[row['profileSha256']] = row
    lines = ['// Generated by generate-apple-everest-stage25kj-guards.py. Do not hand-edit.',
        '#nullable disable', 'using System;', 'using System.Collections.Generic;',
        'using System.Globalization;', 'using System.Runtime.CompilerServices;', 'using Microsoft.Xna.Framework;', 'namespace Celeste.Mod;',
        'internal static class AppleEverestSelectedProfileGuard', '{',
        '    private sealed class Profile', '    {',
        '        internal readonly int Width, Height;',
        '        internal readonly Dictionary<string, object> Values;',
        '        internal readonly Vector2[] Nodes;',
        '        internal Profile(int width, int height, Dictionary<string, object> values, Vector2[] nodes)',
        '        { Width = width; Height = height; Values = values; Nodes = nodes; }',
        '    }', '    private static readonly Dictionary<string, Profile[]> Profiles = new(StringComparer.Ordinal)', '    {']
    for key, group in sorted(profiles.items()):
        lines += ['        [' + cs(key) + '] = new Profile[]', '        {']
        for _, row in sorted(group.items()):
            a = row['attributes']
            entity = row['kind'] != 'backdrop'
            excluded = ('x','y','id','originX','originY','width','height') if entity else ()
            vals = ', '.join('[' + cs(k) + '] = ' + cs(v) for k,v in sorted(a.items()) if k not in excluded)
            nodes = ', '.join('new Vector2(' + cs(float(n['x'] - a.get('x', 0))) + ', ' + cs(float(n['y'] - a.get('y', 0))) + ')' for n in row['nodes'])
            lines.append('            new(' + str(a.get('width', 0)) + ', ' + str(a.get('height', 0)) + ', new(StringComparer.Ordinal) { ' + vals + ' }, new Vector2[] { ' + nodes + ' }),')
        lines += ['        },']
    lines += ['    };', '''
    private sealed class BerryNormalization
    {
        internal readonly Dictionary<string, object> Authored;
        internal readonly int Checkpoint, Order;
        internal BerryNormalization(Dictionary<string, object> authored, int checkpoint, int order)
        { Authored = authored; Checkpoint = checkpoint; Order = order; }
    }
    private static readonly ConditionalWeakTable<EntityData, BerryNormalization> NormalizedBerries = new();

    // MapData assigns tracker coordinates before the factory sees the berry.
    // Validate the authored profile first and retain the exact assignment for
    // this EntityData instance; arbitrary authored coordinates remain rejected.
    internal static void RecordBerryNormalization(EntityData data, int checkpoint, int order)
    {
        if (data.Name != "LunaticHelper/StrawberryWithReturn") return;
        Entity(data.Name, data);
        if (checkpoint < 0 || order < 0) throw Outside(data.Name);
        var authored = new Dictionary<string, object>(AuthoredValues(data), StringComparer.Ordinal);
        NormalizedBerries.Remove(data);
        NormalizedBerries.Add(data, new BerryNormalization(authored, checkpoint, order));
    }

    private static Dictionary<string, object> AuthoredValues(EntityData data)
    {
        if (!NormalizedBerries.TryGetValue(data, out BerryNormalization normalized)) return data.Values;
        if (data.Name != "LunaticHelper/StrawberryWithReturn" || data.Values == null ||
            !data.Values.TryGetValue("checkpointID", out object checkpoint) || checkpoint is not int y || y != normalized.Checkpoint ||
            !data.Values.TryGetValue("order", out object order) || order is not int x || x != normalized.Order)
            throw Outside(data.Name);
        var values = new Dictionary<string, object>(data.Values, StringComparer.Ordinal);
        foreach (string key in new[] { "checkpointID", "order" })
            if (normalized.Authored.TryGetValue(key, out object value)) values[key] = value;
            else values.Remove(key);
        return values;
    }

    internal static void Entity(string id, EntityData data)
    {
        string key = (Profiles.ContainsKey("entity:" + id) ? "entity:" : "trigger:") + id;
        if (data.Name != id || data.Origin != Vector2.Zero || !Profiles.TryGetValue(key, out Profile[] profiles))
            throw Outside(id);
        Dictionary<string, object> values = AuthoredValues(data);
        foreach (Profile profile in profiles)
        {
            if (data.Width != profile.Width || data.Height != profile.Height ||
                !Matches(profile.Values, values) || (data.Nodes?.Length ?? 0) != profile.Nodes.Length) continue;
            bool nodesMatch = true;
            for (int i = 0; i < profile.Nodes.Length; i++)
                if (data.Nodes[i] - data.Position != profile.Nodes[i]) { nodesMatch = false; break; }
            if (nodesMatch) return;
        }
        throw Outside(id);
    }

    internal static void Backdrop(string id, BinaryPacker.Element data)
    {
        if (data.Name == id && (data.Children?.Count ?? 0) == 0 && Profiles.TryGetValue("backdrop:" + id, out Profile[] profiles))
            foreach (Profile profile in profiles)
                if (Matches(profile.Values, data.Attributes)) return;
        throw Outside(id);
    }

    private static bool Matches(Dictionary<string, object> expected, Dictionary<string, object> actual)
    {
        if (expected.Count != (actual?.Count ?? 0)) return false;
        foreach (KeyValuePair<string, object> pair in expected)
        {
            if (!actual.TryGetValue(pair.Key, out object value)) return false;
            if (pair.Value is string || pair.Value is bool)
            { if (!pair.Value.Equals(value)) return false; }
            else
            {
                if (value is not (byte or short or int or float or double) ||
                    Convert.ToSingle(pair.Value, CultureInfo.InvariantCulture) !=
                    Convert.ToSingle(value, CultureInfo.InvariantCulture)) return false;
            }
        }
        return true;
    }

    private static InvalidOperationException Outside(string id) =>
        new InvalidOperationException("factory authored data is outside the reviewed Stage 25K-J profile: " + id);
}''']
    return '\n'.join(lines) + '\n'

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--profiles', type=Path, default=ROOT/'apple-everest/sj-factory-authored-profiles-stage25kj.json')
    p.add_argument('--legacy-profiles', type=Path, default=ROOT/'apple-everest/sj-legacy-factory-profiles-stage25kj.json')
    p.add_argument('--authored-interactions', type=Path, default=ROOT/'apple-everest/sj-authored-interaction-profiles-stage25kj.json')
    p.add_argument('--output', type=Path, default=ROOT/'apple-everest/runtime/semantics/AppleEverestSelectedProfileGuard.cs')
    a = p.parse_args()
    doc = json.loads(a.profiles.read_text())
    legacy = json.loads(a.legacy_profiles.read_text())
    doc['occurrences'] = doc['occurrences'] + legacy['occurrences']
    interactions = json.loads(a.authored_interactions.read_text())
    if interactions['authority'] != 'PROJECT_OWNED_AUTHORED_MECHANISM_FIXTURE_SEPARATE_FROM_ORIGINAL_920':
        raise ValueError('authored interaction ledger authority differs')
    doc['occurrences'] += interactions['occurrences']
    a.output.write_text(generate(doc))
    print('PASS: generated exact typed profile guards')
if __name__ == '__main__': main()
